apiVersion: apps/v1
kind: Deployment
metadata:
  name: intro-component-with-signup-form-app
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: intro-component-with-signup-form-app
  template:
    metadata:
      labels:
        app: intro-component-with-signup-form-app
    spec:
      containers:
        - name: intro-component-with-signup-form-app
          image: intro-component-with-signup-form-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: 'production'
            - name: MAILER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mailer-secrets
                  key: MAILER_API_KEY
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '256Mi'
              cpu: '500m'
          livenessProbe:
            httpGet:
              path: /IntroComponentWithSignupForm/
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /IntroComponentWithSignupForm/
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
